workable visa version
bimdata/platform pull request #108
Opened 2022-01-21 12:35 UTC by pvilalta

Hi there,

This PR marks the first version of the Visa. It's a workable version of the final product and takes feedback from the product owner.

What's news compared to the previous PR

Visa List -> this is a synthesis of all Visa (creator and validator)
Visa Summary (creator view) -> permit for a creator to update / delete / close a visa
UI/UX enhancement
Paul

2022-01-25 09:08 UTC, Kurtil commented on src/components/specific/files/files-manager/FilesManager.scss
> +            gap: var(--spacing-unit);
is the `gap` css property only for display `grid` ?

2022-01-25 09:08 UTC, Kurtil commented on src/components/specific/users/user-avatar/UserAvatar.vue
> +      fontSize: `${sizeInitials ? sizeInitials : +size * 0.382}px`
0.382 ??? ^^

2022-01-25 16:15 UTC, Amoki requested changes

2022-01-25 16:15 UTC, Amoki commented on src/components/specific/files/files-manager/FilesManager.vue
> +                  <span>{{ userVisasCounter || "" }}</span>
Is the `||` used as you check the value in the v-if?

2022-01-25 16:15 UTC, Amoki commented on src/components/specific/users/user-avatar/UserAvatar.vue
> +    sizeInitials: {
`initialsSize`

2022-01-25 16:15 UTC, Amoki commented on src/components/specific/visa/visa-selection-validator/visa-selection-validator-people/VisaSelectionValidatorPeople.vue
> +    v-for="people in userList"
```suggestion
    v-for="user in userList"
```
We usually use `user`

2022-01-25 16:15 UTC, Amoki commented on src/components/specific/visa/visa-summary/VisaSummary.vue
> +                : "utilisateur supprimé",
`this.$t`

2022-01-25 16:15 UTC, Amoki commented on src/config/visa-validation-status.js
> +export default Object.freeze({
Can you define both objects in a single file?

2022-01-25 16:15 UTC, Amoki commented on src/i18n/lang/fr.json
> +      "exempleDate": "(Ex: 31/05/1970)",
```suggestion
      "exempleDate": "(Ex: 31/05/2022)",
```
Histoire de pas faire trop vieux x)

2022-01-25 16:15 UTC, Amoki commented on src/i18n/lang/fr.json
> +        "content": "Êtes-vous sûr de vouloir quitter cette page ? Il y'a peut-être des informations non validées.",
```suggestion
        "content": "Êtes-vous sûr de vouloir quitter cette page ? Il y a peut-être des informations non validées.",
```

2022-01-25 17:13 UTC, NicolasRichel requested changes

2022-01-25 17:13 UTC, NicolasRichel commented on src/components/specific/files/files-manager/FilesManager.vue
> +              </template>
I think you can simplify this part of the template like this:
```html
<div
  v-if="userVisasCounter > 0"
  class="files-manager__actions__visa__content__counter"
>
  <span>{{ userVisasCounter }}</span>
</div>
```

In fact `userVisasCounter` will always be defined and greater than 0 if the div is displayed.

2022-01-25 17:13 UTC, NicolasRichel commented on src/components/specific/visa/visa-safe-zone/VisaSafeZone.vue
>    emits: ["onClose"]
It's usually a good practice to name events with a simple action name, like `close`.
Here `onClose` looks more like an event handler (method) name.

2022-01-25 17:13 UTC, NicolasRichel commented on src/components/specific/visa/visa-summary/visa-summary-people/VisaSummaryPeople.vue
> +                    : "deny"
I think its worth using a computed ref here.

2022-01-25 17:13 UTC, NicolasRichel commented on src/components/specific/visa/visa-summary/visa-summary-people/VisaSummaryPeople.vue
> +                : 'failed'
Same as comment above.
I think it would be a good idea to use a computed property here.

2022-01-25 17:13 UTC, NicolasRichel commented on src/components/specific/visa/visa-summary/visa-summary-people/VisaSummaryPeople.vue
> +        </div>
I see that you use many inline styles here. You could rewrite this in a more concise way:

```html
<div
   class="visa-add-summary-people__right-side__access-denied"
   :class="{ isAuthor }"
   ...
>
   <BIMDataIcon
      class="fill-warning"
      name="warning"
      ...
   />
   <div
      v-if="isWarningHover && currentPeopleId === people.id"
      class="visa-add-summary-people__right-side__access-denied__hover"
   >
      <span>{{ $t("Visa.selectionValidator.warning") }}</span>
   </div>
</div>
```

With the following styles:

```scss
...
   .visa-add-summary-people__right-side__access-denied {
      ...
      right: -12px;
      
      .bimdata-icon {
         z-index: 3; // I'm not sure this is actually useful
         padding: 10px;
      }
      
      &__hover {
         width: 340px;
      }
      
      &.isAuthor {
          right: -8px;
         .visa-add-summary-people__right-side__access-denied__hover {
            right: -36px;
            width: 345px;
         }
      }
   }
...
```

2022-01-25 17:13 UTC, NicolasRichel commented on src/utils/visas.js
> +const getUserList = async ({ baseInfo, fileParentId }, validationList) => {
This function should belong to the visa's state.
Utility functions should be independent from the API / Services.

2022-01-25 17:38 UTC, Amoki requested changes

2022-01-25 17:38 UTC, Amoki commented on src/components/specific/visa/visa-summary/VisaSummary.vue
> +          .map(people => {
`people` vs `user`

2022-01-25 17:38 UTC, Amoki commented on src/components/specific/visa/visa-summary/VisaSummary.vue
> +                userList.value.some(
```javascript
userList.value
  .filter(user => !user.isSelected)
  .some(user => user.id === people.id)
```

2022-01-25 17:38 UTC, Amoki commented on src/components/specific/visa/visa-list/VisaList.vue
> +          <span>{{
```html
<span v-if="currentTab === 'toValidateVisas'">
  {{  $t(Visa.list.emptyValidation)}}
</span>
<span v-else>
  {{  $t(Visa.list.emptyDemand)}}
</span>
```

2022-01-25 17:38 UTC, Amoki commented on src/components/specific/visa/visa-list/VisaList.vue
> +              :style="`${
template string is useless here

2022-01-25 17:38 UTC, Amoki commented on src/components/specific/visa/visa-list/VisaList.vue
> +              visa.status === visaClosed
in a computed

2022-01-25 17:38 UTC, Amoki commented on src/components/specific/visa/visa-summary/visa-summary-people/VisaSummaryPeople.vue
> +                    : people.status === VALIDATION_STATUS.PENDING
can we use `VALIDATION_STATUS.ACCEPT ` in the json instead of "active" ?

2022-01-25 17:38 UTC, Amoki commented on src/utils/visas.js
> +    .map(people => ({
```suggestion
    .map(user => ({
```

2022-01-25 17:38 UTC, Amoki commented on src/utils/visas.js
> +    .filter(({ isSelf }) => !isSelf);
filter before map

2022-01-25 17:38 UTC, Amoki commented on src/utils/visas.js
> +      searchContent: `${people.firstname || ""}${people.lastname || ""}${
add spaces between values

2022-01-31 08:31 UTC, NicolasRichel approved these changes

2022-01-31 08:33 UTC, Amoki requested changes

2022-01-31 08:33 UTC, Amoki commented on src/components/specific/files/files-manager/FilesManager.vue
> +            ) || [],
I think the `|| []` is useless in this situation

2022-01-31 08:33 UTC, Amoki commented on src/components/specific/files/files-manager/FilesManager.vue
> +            ) || []
idem

2022-01-31 08:33 UTC, Amoki commented on src/components/specific/files/files-manager/FilesManager.vue
> +              <template v-if="userVisasCounter > 0">
```suggestion
              <template v-if="userVisas.toValidateVisas.length || userVisas.createdVisas.length">
```
This way, you don't need to create `userVisasCounter` at all

2022-01-31 09:01 UTC, Amoki requested changes

2022-01-31 09:01 UTC, Amoki commented on src/config/visa-validation-status.js
> +export default Object.freeze({
up

2022-01-31 09:01 UTC, Amoki commented on src/components/specific/visa/visa-summary/VisaSummary.vue
> +    const fetchAllVisaInfo = async visa => {
fetchDocumentUsers

2022-01-31 09:01 UTC, Amoki commented on src/components/specific/visa/visa-summary/VisaSummary.vue
> +      await fetchAllVisaInfo(props.visa);
formatedVisa.value = formatVisa(props.visa);
userProjectList.value = await fetchDocumentUsers(props.visa);

2022-01-31 10:38 UTC, Amoki requested changes

2022-01-31 10:38 UTC, Amoki commented on src/components/specific/visa/visa-summary/visa-summary-validator/VisaSummaryValidator.vue
> +import { userValidationStatus as VALIDATION_STATUS } from "@/config/visa";
You can directly name those variables `VALIDATION_STATUS` is the config file to avoid renaming here

2022-02-01 10:49 UTC, Amoki approved these changes

2022-02-01 13:06 UTC, merged