Feature/guided tour
bimdata/platform pull request #181
Opened 2022-04-06 13:09 UTC by pvilalta

https://platform-dev-guided-tour.bimdata.io

Hello team,

Here is the initial version of the guided tour. It's integrated in the platform without any condition, thats mean each time you will start the platform or refresh it, the guided tour will occur.

What I have done

* created a specific component for the first and last step
* made up a basic scenario to use the component

things to improve

* ~manage if 2 or more tours are available at the same time~
* ~manage if the user has already watched a tour~
* ~flag a specific element with 'data-guide" that come from an iteration (I made a simple implementation here, that spotlight the first element only)~

This PR is related with the one on the design-system that I also pushed
https://github.com/bimdata/design-system/pull/173

To test the feature you have to pull the branch from the design-system and either

* build and copy/paste dist file into the platform
or
* build and create a relation between the platform and the design-system ("@bimdata/design-system": "file:../design-system")

It's not the intent to merge this PR in develop currently, more update will occur over time (through sub PR)

2022-04-06 13:11 UTC, NicolasRichel approved these changes

2022-04-20 09:08 UTC, NicolasRichel requested changes

2022-04-20 09:08 UTC, NicolasRichel commented on src/state/user.js
> +  return guidedTour.json();
I think the `.json()` deserialization should be done in the service rather than the state.

2022-04-20 09:15 UTC, Amoki requested changes

2022-04-20 09:15 UTC, Amoki commented on src/services/PlatformService.js
> +  completedTour(accessToken, tour) {
What about `setTourCompleted` ?

2022-04-20 09:31 UTC, NicolasRichel approved these changes

2022-04-20 09:44 UTC, Amoki requested changes

2022-04-20 09:44 UTC, Amoki commented on src/services/PlatformService.js
> +    const res = fetch(`${process.env.VUE_APP_BACKEND_BASE_URL}/guidedtour/`, {
```suggestion
    const res = await fetch(`${process.env.VUE_APP_BACKEND_BASE_URL}/guidedtour/`, {
```

2022-04-20 09:44 UTC, Amoki commented on src/state/user.js
> +  const { accessToken } = useAuth();
AccessToken can be managed directly in the service, see https://github.com/bimdata/platform-next/blob/develop/src/services/BcfService.js#L32

2022-04-20 13:18 UTC, Amoki approved these changes

2022-04-21 06:45 UTC, NicolasRichel approved these changes

2022-04-27 14:39 UTC, NicolasRichel approved these changes

2022-04-27 15:15 UTC, merged

2024-10-16 12:28 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: