Visa/improvement
bimdata/platform pull request #200
Opened 2022-04-25 12:54 UTC by pvilalta

hello team,

This PR cover issues about Visa, each of them are related to a ticket

- [remove closed Visa from notification counter](https://github.com/bimdata/platform-next/issues/197)
- [keyboard shortcut made push commentary twice](https://github.com/bimdata/platform-next/issues/193)
- [struggle with commentary input](https://github.com/bimdata/platform-next/issues/191)
- [search-bar cancel box that are ticked](https://github.com/bimdata/platform-next/issues/190)

Paul

2022-04-25 13:35 UTC, NicolasRichel requested changes

2022-04-25 13:35 UTC, NicolasRichel commented on src/components/specific/visa/visa-selection-validator/VisaSelectionValidator.vue
> +        .filter(({ isFindable }) => isFindable)
Couldn't this (`map` + `filter`) be replaced by that:
```js
peopleList.value = (updatedSelection.value || props.userList)
   .filter(people =>
      filter.value === ""
         ? true
         : people.searchContent.includes(filter.value.toLowerCase())
   )
   .sort( ... )
```

2022-04-25 14:01 UTC, pvilalta commented on src/components/specific/visa/visa-selection-validator/VisaSelectionValidator.vue
> +        .filter(({ isFindable }) => isFindable)
it would have worked this way
I finally choose to slightly re-design the way of the logic works because an error has occurred when i was testing your solution (a behavior that I did not cover before)
I commit some changes, It's working well now

2022-04-25 16:18 UTC, NicolasRichel approved these changes

2022-04-26 07:06 UTC, merged

2024-10-16 12:28 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: