visa / fit API new data structure
bimdata/platform pull request #209
Opened 2022-05-04 08:54 UTC by pvilalta

Hello team,

Since API send back a new data structure about visa, this PR permits to handle this new informations in order to make Visa works 

Paul

2022-05-04 13:50 UTC, NicolasRichel requested changes

2022-05-04 13:50 UTC, NicolasRichel commented on src/state/visa.js
> +  const { getDocument } = useFiles();
Here you can call `FilesService` directly as you are already in the state and you don't need to perform any other operation, just get the document from the API.

2022-05-04 13:50 UTC, NicolasRichel commented on src/state/files.js
> +};
This method is not necessary because you can call `FilesService` directly from the visa state.

2022-05-04 14:26 UTC, Amoki approved these changes

2022-05-04 14:27 UTC, merged

2024-10-16 12:28 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: