feature / versioning
bimdata/platform pull request #214
Opened 2022-05-12 06:57 UTC by pvilalta

Hello team,

This PR brings the versioning feature

Paul

2022-05-13 07:45 UTC, amineau commented
https://platform-dev-versioning.bimdata.io/

2022-05-13 08:07 UTC, NicolasRichel requested changes

2022-05-13 08:07 UTC, NicolasRichel commented on src/components/specific/versioning/versioning-main/VersioningMain.vue
> +          <template v-for="(doc, index) of allDocVersions" :key="index">
I see an **index** as `key` here.
Did you check that it does not result in the same bug that we discuss last time ?
(As a reminder: the UI was not properly updated when deleting the first element due to the way Vue uses `key` attribute internally to identify nodes).

2022-05-24 07:36 UTC, GabBimdata approved these changes

2022-05-25 09:25 UTC, Kurtil requested changes

2022-05-25 09:25 UTC, Kurtil commented on src/components/specific/files/files-manager/FilesManager.vue
> +      setTimeout(() => {
Why is there a setTimout here ? Can a $nextTick work instead ?

2022-05-25 09:31 UTC, pvilalta commented on src/components/specific/files/files-manager/FilesManager.vue
> +      setTimeout(() => {
nextTick work as well, but for a smoother transition setTimeout is better

2022-05-25 10:53 UTC, Kurtil approved these changes

2022-05-30 12:37 UTC, NicolasRichel approved these changes

2022-05-30 12:39 UTC, merged

2024-10-16 12:28 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: