[WIP] GED / folder import
bimdata/platform pull request #277
Opened 2022-08-30 07:26 UTC by pvilalta

2022-08-30 07:55 UTC, NicolasRichel requested changes

2022-08-30 07:55 UTC, NicolasRichel commented on src/i18n/lang/fr.json
> +    "folderImport": "Import un dossier",
There is a typo here: "*Import*" instead of "*Importer*"

2022-08-30 07:55 UTC, NicolasRichel commented on src/utils/projects.js
> +  treeIdGenerator
I think these new functions should be in the **files** utils instead of project utils.

2022-08-30 08:31 UTC, Amoki requested changes
![image](https://user-images.githubusercontent.com/1349751/187389186-025e79af-ae2a-45a1-bd3a-b27b3201e3f6.png)
After a folder upload, the folder stays in the upload mode and I can't use it.

2022-09-01 12:13 UTC, Amoki requested changes

2022-09-01 12:13 UTC, Amoki commented on src/components/specific/files/file-upload-card/FileUploadCard.vue
> +        progress.onGoingUploadCounter--;
```suggestion
        progress.onGoingUploadsCounter--;
```

2022-09-01 12:25 UTC, Amoki requested changes

2022-09-01 12:25 UTC, Amoki commented on src/utils/upload.js
> +  input.click();
Is the input cleared somewhere or it stays in the dom?

2022-09-01 14:29 UTC, Amoki approved these changes

2022-09-01 14:34 UTC, merged

2024-10-16 12:27 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: