fix(build): put static assets into 'public' directory
bimdata/platform pull request #295
Opened 2022-10-10 06:09 UTC by NicolasRichel

2022-10-10 06:50 UTC, Amoki requested changes

2022-10-10 06:50 UTC, Amoki commented on vite.config.js
> +  build: {
debug?

2022-10-10 06:55 UTC, NicolasRichel commented on vite.config.js
> +  build: {
Yes, this is still work in progress. :)

2022-10-12 12:55 UTC, merged

2024-10-16 12:26 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: