feature / invitation
bimdata/platform pull request #298
Opened 2022-10-13 08:58 UTC by pvilalta

2022-10-13 09:06 UTC, Kurtil approved these changes

2022-10-13 12:50 UTC, Amoki requested changes

2022-10-13 12:50 UTC, Amoki commented on src/config/invitation.js
> +  ACCEPT: "A",
ACCEPTED

2022-10-13 12:50 UTC, Amoki commented on src/config/invitation.js
> +  DENY: "D"
DENIED

2022-10-13 12:50 UTC, Amoki commented on src/views/invitation/Invitation.vue
> +    onMounted(async () => fetchInvitations());
useless async

2022-10-13 12:50 UTC, Amoki commented on src/views/invitation/Invitation.vue
> +                    @click="onDenyInvitation(invit).then(fetchInvitations)"
Handling async stuff in the template seems complex.
Do we want to call `fetchInvitations()` in the function `onDenyInvitation()` ?
@Kurtil

2022-10-13 12:50 UTC, Amoki commented on src/config/invitation.js
> +const INVITATION_VALIDATION_STATUS = Object.freeze({
`INVITATION_STATUS`
There is no "validation" concept in an invitation imho

2022-10-13 14:24 UTC, pvilalta commented
PR in draft mod to resolve all team feedbacks

2022-10-18 14:23 UTC, Kurtil requested changes

2022-10-18 14:23 UTC, Kurtil commented on src/router/guards/data.js
> +    ]);
I don't think the comments are usefull here... The functions are well named, and you await them so yes it is important to await them before calling the following. The comments are juste describing what the code already tells you :)

2022-10-18 14:44 UTC, Kurtil approved these changes

2022-10-18 14:44 UTC, Kurtil commented on src/router/guards/data.js
> +    ]);
The code i commented is not from this PR... my bad

2022-10-20 13:29 UTC, Amoki approved these changes

2022-10-20 13:49 UTC, NicolasRichel requested changes

2022-10-20 13:49 UTC, NicolasRichel commented on src/router/index.js
> +        path: "/invitation",
To be consistent with the general naming convention of the project I would recommend to use a plural form for this route: `/invitations`.

2022-10-20 13:49 UTC, NicolasRichel commented on src/router/index.js
> +        component: Invitation,
The same apply to route name and component name: `Invitations`.

2022-10-20 13:49 UTC, NicolasRichel commented on src/state/invitations.js
> +  await loadUserInvitations();
Why does `loadUserInvitations()` isn't inside `Promise.all` ?
Is it necessary to call it seperately ?

2022-10-20 13:49 UTC, NicolasRichel commented on src/views/invitation/Invitation.vue
> +      getBack: () => router.back(),
Is this method still needed ? I can't find were you use it.

2022-10-20 15:13 UTC, NicolasRichel approved these changes

2022-10-26 08:04 UTC, GabBimdata approved these changes

2022-10-26 08:05 UTC, merged

2024-10-16 12:26 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: