GED onboarding view / add import GED and upload folder
bimdata/platform pull request #301
Opened 2022-10-24 06:48 UTC by pvilalta

2022-10-24 07:05 UTC, NicolasRichel approved these changes

2022-10-24 07:51 UTC, Kurtil requested changes

2022-10-24 07:51 UTC, Kurtil commented on src/services/FileService.js
> +    return async.map(currentFiles, async folder => {
[Promise.allSettled()](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) ?

2022-10-24 07:51 UTC, Kurtil commented on src/components/specific/files/files-manager/FilesManager.vue
>          await async.each(Array.from(event.dataTransfer.items), async file => {
[Promise.all](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) ?

2022-10-24 13:38 UTC, Kurtil approved these changes

2022-10-25 08:36 UTC, GabBimdata approved these changes

2022-10-25 08:53 UTC, merged

2024-10-16 12:26 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: