feat(models): add point-cloud tab to models manager
bimdata/platform pull request #304
Opened 2022-10-27 11:56 UTC by NicolasRichel

2022-10-27 11:59 UTC, Amoki requested changes

2022-10-27 11:59 UTC, Amoki commented on src/config/viewer.js
> +  tileset: true,
you also have to add "tileset-viewer-parameters".
I think we want them enabled by default in viewer now

2022-10-27 12:11 UTC, pvilalta approved these changes

2022-10-27 12:25 UTC, Amoki approved these changes

2022-10-27 13:10 UTC, merged

2024-10-16 12:26 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: