Feature: export bcf topic selection
bimdata/platform pull request #308
Opened 2022-11-16 16:37 UTC by NicolasRichel

2022-11-16 16:39 UTC, LrxGaelle approved these changes

2022-11-17 10:19 UTC, Amoki requested changes

2022-11-17 10:19 UTC, Amoki commented on src/i18n/lang/en.json
> +        "selectedTopicCount": "Selected topics",
en and fr translations don't mean the same

2022-11-17 10:27 UTC, Amoki approved these changes

2022-11-17 10:32 UTC, merged

2024-10-16 12:25 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: