[WIP] Fix: vite config
bimdata/platform pull request #334
Opened 2022-12-21 08:12 UTC by NicolasRichel

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have tested my code.

2022-12-21 08:46 UTC, Kurtil approved these changes

2022-12-21 08:59 UTC, amineau requested changes

2022-12-21 08:59 UTC, amineau commented on package.json
> +    "vite": "3.2.5",
I removed "^" prefix to fix `vite` version. We can now add it again

2022-12-21 09:07 UTC, amineau approved these changes

2022-12-21 09:20 UTC, merged

2024-10-16 12:25 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: