ged / import user groups
bimdata/platform pull request #341
Opened 2023-01-10 12:36 UTC by pvilalta

## Description

One point that I would like to discuss
With BIMDataMenu component, if 2 items has the same name and has children, when one is over both display their children.
In my case, if 2 projects has the same name, this limitation will occurs.

any thought ? 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have tested my code.

2023-01-10 13:25 UTC, NicolasRichel requested changes

2023-01-10 13:25 UTC, NicolasRichel commented on src/components/specific/groups/group-import/GroupImport.vue
> +    const importGroup = async children => {
This function looks like something that can be "lifted up" into the state directly.
Let's have a talk about that when you have a moment. ;)

2023-01-10 14:41 UTC, NicolasRichel approved these changes

2023-01-12 15:20 UTC, NicolasRichel approved these changes

2023-01-13 15:56 UTC, NicolasRichel approved these changes

2023-01-13 16:02 UTC, Kurtil requested changes

2023-01-13 16:02 UTC, Kurtil commented on src/components/specific/groups/group-import/GroupImport.vue
> +              Boolean(
`Boolean(arr.find(func))` => `arr.some(func)`

2023-01-13 16:02 UTC, Kurtil commented on src/components/specific/groups/group-import/GroupImport.vue
> +              Boolean(
In this case the `Boolean()` call may be still used to parse undefined into false.

2023-01-13 16:18 UTC, Kurtil approved these changes

2023-01-16 22:18 UTC, GabBimdata approved these changes

2023-01-17 08:18 UTC, NicolasRichel approved these changes

2023-01-17 08:19 UTC, merged

2024-10-16 12:24 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: