ged / drag-and-drop file in specific folder
bimdata/platform pull request #346
Opened 2023-01-17 08:45 UTC by pvilalta

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have tested my code.

2023-01-17 09:19 UTC, Kurtil commented on src/components/specific/groups/group-card/group-card-delete-guard/GroupCardDeleteGuard.vue
> +        <template #name>
:P

2023-01-17 09:22 UTC, Kurtil requested changes

2023-01-17 09:22 UTC, Kurtil commented on src/services/FileService.js
> +            return (rootFolderNode = node);
return an affectation ?

2023-01-17 09:22 UTC, Kurtil commented on src/services/FileService.js
> +          return node.children?.forEach(getRootFolderNode);
forEach returns `undefined`.

2023-01-17 09:55 UTC, Kurtil approved these changes

2023-01-19 08:53 UTC, NicolasRichel approved these changes

2023-03-09 08:29 UTC, NicolasRichel commented
Replaced with #361

2023-03-09 08:29 UTC, closed without merging