Feature/use bim data menu component
bimdata/platform pull request #351
Opened 2023-01-26 15:53 UTC by LrxGaelle

## Description
Use BIMDataMenu component

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have tested my code.

2023-01-26 16:42 UTC, NicolasRichel requested changes

2023-01-26 16:42 UTC, NicolasRichel commented on src/components/specific/files/files-table/file-actions-cell/FileActionsCell.vue
> +    if (
This `if` statement refers to the exact same condition as the previous one.
I think we could merge them into one.

2023-01-26 16:42 UTC, NicolasRichel commented on src/components/specific/files/files-table/file-actions-cell/FileActionsCell.vue
> +    if (
**Note:** you can also use the [`hasAdminPerm` helper](https://github.com/bimdata/platform-next/blob/develop/src/utils/file-structure.js#L288) to simplify the code here. ;)

2023-01-26 17:17 UTC, NicolasRichel approved these changes

2023-01-27 08:44 UTC, Kurtil approved these changes

2023-02-16 14:24 UTC, GabBimdata approved these changes

2023-03-02 17:33 UTC, merged

2024-10-16 12:24 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: