Fix: folder upload
bimdata/platform pull request #361
Opened 2023-03-09 08:28 UTC by NicolasRichel

## Description

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have tested my code.

2023-03-09 09:24 UTC, Kurtil requested changes

2023-03-09 09:24 UTC, Kurtil commented on src/components/specific/files/files-manager/FilesManager.vue
> +            @manage-access="openAccessManager($event)"
Other methods are bounded to handlers without the `$event`

2023-03-09 09:24 UTC, Kurtil commented on src/components/specific/files/files-manager/FilesManager.vue
> +          async f =>
No need to async await here.

2023-03-09 09:24 UTC, Kurtil commented on src/components/specific/files/files-manager/files-manager-onboarding/FilesManagerOnboarding.vue
> +            await FileService.createFolderStructure(
No need for async await here.

2023-03-09 09:24 UTC, Kurtil commented on src/utils/files.js
> +async function getFileFromFileEntry(entry) {
remove `async`

2023-03-09 09:24 UTC, Kurtil commented on src/utils/files.js
> +async function getEntriesFromDirEntry(entry) {
remove `async`

2023-03-09 09:24 UTC, Kurtil commented on src/utils/files.js
> +        async e => await parseDirEntry(e, {}, files).then(res => res.tree)
No need for `async/await` here.

2023-03-09 09:24 UTC, Kurtil commented on src/utils/files.js
> +    Array.from(event.dataTransfer.items)
Second argument of `Array.from` is a map function... it may be more performant to use it instead of a direct `.map` call after it.

2023-03-09 09:24 UTC, Kurtil commented on src/utils/files.js
> +  const asyncFolders = dirEntries.map(async e => await parseDirEntry(e));
No need for `async/await` here.

2023-03-09 09:30 UTC, Kurtil commented on src/utils/files.js
> +    Array.from(event.dataTransfer.items)
A simple [jsbench](https://jsben.ch/G0ha3) seems to validate what I said :) (chrome + firefox)

2023-03-09 15:02 UTC, Kurtil approved these changes

2023-03-13 13:16 UTC, Amoki approved these changes

2023-03-13 13:19 UTC, merged

2024-10-16 12:24 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: