Fix: folder default permission
bimdata/platform pull request #364
Opened 2023-03-14 13:49 UTC by NicolasRichel

## Description

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have tested my code.
- [x] I want to run the tests for the commits of this PR

2023-03-14 14:18 UTC, Kurtil commented on src/components/specific/files/folder-access-manager/group-permission-selector/GroupPermissionSelector.vue
>      watch(
Isn't it the best place for a `watchEffect` instead ?

2023-03-14 15:18 UTC, Amoki commented on src/i18n/lang/fr.json
We have to make sure i18n stays is sync. We have new translations with same tokens

2023-03-15 07:02 UTC, NicolasRichel commented on src/i18n/lang/fr.json
Translations will be marked as "fuzzy" in POEditor.
I'll fix them when the PR is merged.

2023-04-25 21:19 UTC, Kurtil requested changes

2023-04-25 21:19 UTC, Kurtil commented on src/components/specific/files/folder-access-manager/FolderAccessManager.vue
> +    onMounted(() => loadFolderInfo());
Is the arrow function useful ?

2023-04-25 21:19 UTC, Kurtil commented on src/state/groups.js
> +  return await GroupService.updateGroupPermission(project, folder, group, data);
`async/await` may not be needed here.

2023-04-26 06:38 UTC, Amoki commented on src/state/groups.js
> +  return await GroupService.updateGroupPermission(project, folder, group, data);
```javascript
const updateGroupPermission = GroupService.updateGroupPermission;
```
It does the same, no?

2023-04-26 07:35 UTC, NicolasRichel commented on src/state/groups.js
> +  return await GroupService.updateGroupPermission(project, folder, group, data);
yep

2023-04-26 07:35 UTC, NicolasRichel commented on src/components/specific/files/folder-access-manager/FolderAccessManager.vue
> +    onMounted(() => loadFolderInfo());
I don't think so.

2023-05-26 08:58 UTC, merged

2024-10-16 12:22 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: