Fix/export import bcf
bimdata/platform pull request #366
Opened 2023-03-15 17:14 UTC by LrxGaelle

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have tested my code.
- [x] I want to run the tests for the commits of this PR

2023-03-16 07:54 UTC, NicolasRichel approved these changes

2023-03-16 09:30 UTC, Amoki requested changes

2023-03-16 09:30 UTC, Amoki commented on src/state/bcf.js
> +  return await service.exportBcf(project, topics);
you can remove `async` and `await here`

2023-03-16 09:32 UTC, Amoki approved these changes

2023-03-17 08:19 UTC, GabBimdata approved these changes

2023-03-20 12:25 UTC, Amoki approved these changes

2023-03-20 14:50 UTC, Kurtil approved these changes

2023-03-21 08:49 UTC, merged

2024-10-16 12:23 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: