add preview for office files
bimdata/platform pull request #375
Opened 2023-04-26 10:46 UTC by Amoki

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have tested my code.
- [x] I want to run the tests for the commits of this PR

2023-04-26 11:58 UTC, NicolasRichel requested changes

2023-04-26 11:58 UTC, NicolasRichel commented on src/components/specific/files/document-viewer/DocumentViewer.vue
> +const OFFICE_FILES = [".ppt",".pptx",".odp",".xls",".xlsx",".ods",".doc",".docx",".odt"]
This extension list could be moved into the files config: `src/config.files.js`.

2023-04-26 12:20 UTC, Kurtil requested changes

2023-04-26 12:20 UTC, Kurtil commented on src/components/specific/files/document-viewer/DocumentViewer.vue
> +    case ".ppt":
Maybe the switch is not relevant here as you have to repeat all `OFFICE_FILES`. Use `arr.some` instead ?

2023-04-26 12:32 UTC, NicolasRichel approved these changes

2023-04-27 13:09 UTC, merged

2024-10-16 12:23 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: