feat(perf): lazy load project cards
bimdata/platform pull request #389
Opened 2023-06-09 13:48 UTC by NicolasRichel

https://platform-dev-perf-user-projects.bimdata.io

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have tested my code.
- [x] I want to run the tests for the commits of this PR

2023-06-12 08:12 UTC, Kurtil requested changes

2023-06-12 08:12 UTC, Kurtil commented on src/components/specific/projects/project-card/ProjectCard.vue
> +        async ([{ isIntersecting }]) => {
useless `async`

2023-06-12 13:54 UTC, Amoki commented
There is a blink effect when the placeholder car is replaced by the real card.

The placeholder disappears with an animation leaving the space empty, then the card arrives with another animation.

2023-06-14 08:53 UTC, Amoki approved these changes

2023-06-14 09:07 UTC, Kurtil approved these changes

2023-06-14 12:18 UTC, Amoki approved these changes

2023-07-19 08:08 UTC, merged

2024-10-16 12:22 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: