[WIP] Fix/import group feature
bimdata/platform pull request #431
Opened 2023-12-14 15:26 UTC by LrxGaelle

## Description

Redesign import group menu

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have tested my code.
- [x] I want to run the tests for the commits of this PR

2023-12-14 15:54 UTC, GabBimdata approved these changes

2023-12-14 16:32 UTC, Amoki requested changes

2023-12-14 16:32 UTC, Amoki commented on src/i18n/lang/en.json
> +    "noProject": "You have no other project.",
No `.` at the end of sentences

2023-12-15 09:00 UTC, Amoki approved these changes

2023-12-15 13:16 UTC, NicolasRichel requested changes

2023-12-15 13:16 UTC, NicolasRichel commented on src/components/specific/groups/group-import/GroupImport.vue
> +        <template v-if="filteredProjectsToDisplay.length === 0">
It should be a `v-else-if` here in order to avoid both messages to be displayed simultaneously.

2023-12-18 08:29 UTC, NicolasRichel approved these changes

2023-12-21 10:43 UTC, merged

2024-10-16 12:21 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: