[WIP] Feature/flat ged destination
bimdata/platform pull request #457
Opened 2024-06-07 16:21 UTC by LrxGaelle

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have tested my code.
- [x] I want to run the tests for the commits of this PR

2024-06-20 15:04 UTC, NicolasRichel approved these changes

2024-07-24 14:40 UTC, GabBimdata approved these changes

2024-07-24 14:49 UTC, Kurtil approved these changes

2024-07-25 10:02 UTC, NicolasRichel requested changes

2024-07-25 10:02 UTC, NicolasRichel commented on src/components/specific/files/files-table/file-name-cell/FileNameCell.scss
> +  // max-width: calc(773.5px - (var(--spacing-unit) * 2));
Commented code here. ;)

2024-07-25 12:15 UTC, NicolasRichel approved these changes

2024-07-25 12:22 UTC, merged

2024-10-16 12:20 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: