[WIP] Feature/ged visas view
bimdata/platform pull request #459
Opened 2024-06-19 15:49 UTC by LrxGaelle

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have tested my code.
- [x] I want to run the tests for the commits of this PR

2024-07-10 09:27 UTC, GabBimdata approved these changes

2024-07-29 08:38 UTC, GabBimdata approved these changes

2024-07-31 09:18 UTC, Kurtil approved these changes

2024-07-31 09:29 UTC, NicolasRichel requested changes

2024-07-31 09:29 UTC, NicolasRichel commented on tests/e2e/specs/features/06_docimport.cy.js
> +    cy.get("body > input[type=file]", { timeout: 10000 }).should("exist");
I think this line is not needed anymore.

2024-07-31 09:29 UTC, NicolasRichel commented on tests/e2e/specs/features/02_invitations.cy.js
> +    cy.hook("btn-accept-all-invit", { timeout: 60000 }).click();
Is this timeout really useful ?
This test used to pass without problem before and it doesn't like your modifications have impacted that part of the code.

2024-07-31 09:41 UTC, NicolasRichel approved these changes

2024-07-31 15:56 UTC, merged

2024-10-16 12:20 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: