[WIP] Feature: Photopshere Viewer
bimdata/platform pull request #461
Opened 2024-06-28 09:45 UTC by NicolasRichel

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have tested my code.
- [x] I want to run the tests for the commits of this PR

2024-11-22 15:25 UTC, GabBimdata commented
It seems to be working well; however, we have some issues with the BCF. It doesn't load the correct photo nor position the camera properly when trying to view a BCF on a 360 photo. @NicolasRichel

2024-11-22 15:26 UTC, GabBimdata requested changes
cf my comment

2024-11-29 12:25 UTC, Amoki commented on src/components/specific/files/files-table/file-actions-cell/FileActionsCell.vue
> +      if (!isFolder(props.file) && isConvertibleToPhotosphere(props.file)) {
why not an if with 3 conditions?

2024-12-05 13:50 UTC, Kurtil approved these changes

2024-12-05 13:50 UTC, Kurtil commented on src/state/models.js
> +
```suggestion
const createPhotosphere = (project, file) => ModelService.createPhotosphere(project, file);

```

2025-01-09 17:26 UTC, merged

2025-02-17 14:05 UTC, Bimdata-io commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: