fix(users): apply search filter to both users and invitations
bimdata/platform pull request #464
Opened 2024-07-23 12:41 UTC by NicolasRichel

## Description

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have tested my code.
- [x] I want to run the tests for the commits of this PR

2024-07-23 12:50 UTC, Kurtil requested changes

2024-07-23 12:50 UTC, Kurtil commented on src/components/specific/users/project-users-manager/ProjectUsersManager.vue
> +      if (showUserSearch) setTimeout(() => searchInput.value.focus());
missing `.value` here !
... and why not nextTick instead of setTimeout ??

2024-07-23 12:51 UTC, Kurtil commented on src/components/specific/users/project-users-manager/ProjectUsersManager.vue
> +      if (showUserSearch) setTimeout(() => searchInput.value.focus());
`showUserSearch.value` instead of `showUserSearch`

2024-07-23 12:59 UTC, Kurtil commented on src/components/specific/users/project-users-manager/ProjectUsersManager.vue
> +      if (showUserSearch.value) setTimeout(() => searchInput.value.focus());
why `settimeout` ? vue may just need a `nextTick` here doesnt it ?

2024-07-23 13:01 UTC, Kurtil approved these changes

2024-07-24 09:53 UTC, GabBimdata approved these changes
Great ! That works perfectly for me :)

2024-07-25 14:31 UTC, merged

2024-10-16 12:20 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: