fix location
bimdata/platform pull request #465
Opened 2024-08-28 15:49 UTC by Amoki

## Description

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] My code follows the code style of this project.
- [x] I have tested my code.
- [x] I want to run the tests for the commits of this PR

2024-08-28 15:57 UTC, Kurtil approved these changes

2024-08-28 16:31 UTC, NicolasRichel requested changes

2024-08-28 16:31 UTC, NicolasRichel commented on src/utils/location.js
> +  console.log("DD2DMS:", lat, long)
Looks like your left some dev logs. ;)

2024-08-28 16:31 UTC, NicolasRichel commented on src/utils/location.js
> +  console.log("latitude:", [latD, latM, latS, latDir])
dev logs ?

2024-08-28 16:31 UTC, NicolasRichel commented on src/utils/location.js
> +  console.log("longitude:", [longD, longM, longS, longDir])
dev logs ?

2024-08-28 16:31 UTC, NicolasRichel commented on src/utils/location.js
> + *   When the direction is West or South, all components me negative. When direction is East or North, all components are negatives.
Shouldn't that sentence be:
> When the direction is West or South, all components **are** negative. When direction is East or North, all components are **positive**.

2024-08-29 07:18 UTC, NicolasRichel approved these changes

2024-09-02 12:14 UTC, merged

2024-10-16 12:20 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: