add disabled state to open viewer btn
bimdata/platform pull request #491
Opened 2024-12-12 13:11 UTC by LrxGaelle

## Description

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) DON'T FORGET TO SEND THE PR INTO RELEASE
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have tested my code.
- [x] I want to run the tests for the commits of this PR

2024-12-12 13:44 UTC, NicolasRichel approved these changes

2024-12-16 13:20 UTC, Amoki requested changes

2024-12-16 13:20 UTC, Amoki commented on src/components/specific/models/models-card/ModelsCard.vue
> +        <BIMDataButton color="primary" fill radius :disabled="currentModel.status === 'I'">
```suggestion
        <BIMDataButton color="primary" fill radius :disabled="currentModel.status !== 'C'">
```

2024-12-17 11:16 UTC, Amoki approved these changes

2024-12-17 12:58 UTC, NicolasRichel approved these changes

2024-12-17 14:03 UTC, GabBimdata approved these changes

2024-12-17 14:04 UTC, merged

2025-01-07 09:49 UTC, Bimdata-io commented
:tada: This PR is included in version 1.1.1 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: