Feature: payment
bimdata/platform pull request #79
Opened 2021-10-20 05:56 UTC by NicolasRichel

As discussed yesterday, I would like to merge a first (unfinished) draft with **payment** features that are already implemented.
This includes:
 - Organizations Management ~(still some bugs)~
 - Subscriptions view (with the list of billings and invoices)
 - "Upgrade Storage" buttons on Space board and Project board

The Payment view (with payment form) is not implemented yet.

2021-10-20 08:22 UTC, LrxGaelle approved these changes

2021-10-20 08:47 UTC, Amoki requested changes

2021-10-20 08:47 UTC, Amoki commented on src/components/specific/organizations/organizations-manager/organization-spaces-list/organization-space-card/OrganizationSpaceCard.scss
> +        // &::before {
dead code ?

2021-10-20 08:47 UTC, Amoki commented on src/utils/files.js
> +function formatBytesV2(bytes, decimals = 2) {
Do we want to keep `formatBytes()`? This one seems better in all cases.
And it would avoid this weird naming

2021-10-20 08:47 UTC, Amoki commented on src/views/space-board/SpaceBoard.vue
> +          <!-- <BIMDataButton
dead code ?

2021-12-16 08:34 UTC, NicolasRichel commented
Payment Feature finalized, ready to be merged. :)

2021-12-16 08:40 UTC, merged

2024-10-16 12:30 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: