start to the active directory / can't move a file to the folder where…
bimdata/platform pull request #84
Opened 2021-11-15 14:26 UTC by pvilalta

Hello all!

I made same modifications into the moveTo window 
* The starting directory is now the active one, where the user is
* It's impossible to move a file into the folder where it is currently

Paul

2021-11-15 14:37 UTC, Amoki commented on src/components/specific/files/folder-selector/FolderSelector.vue
> +        if (selectedFolder.value) {
For branlette intellectuelle only, how could you replace this `if` with a fully functional method?

2021-11-15 14:56 UTC, pvilalta commented on src/components/specific/files/folder-selector/FolderSelector.vue
> +        if (selectedFolder.value) {
here is my proposition 

```js
  const isAllowedToMoveFile = computed(() =>
    props.files.some(f =>
      selectedFolder.value
        ? selectedFolder.value.id === f.parentId
        : currentFolder.value.id === f.parentId
    )
  );
 ```
this code has been tested

2021-11-15 14:57 UTC, Amoki commented on src/components/specific/files/folder-selector/FolderSelector.vue
> +        if (selectedFolder.value) {
This is still a condition. I meant without using any condition (no  `if` nor ternary)

2021-11-15 15:15 UTC, Amoki requested changes

2021-11-15 15:15 UTC, Amoki commented on src/components/specific/files/folder-selector/FolderSelector.vue
> +        if (selectedFolder.value) {
Forget my previous comments.

The `if` is computed for each file and there is no way the `selectedFolder` value can change during the loop. You should set a variable before the loop.

2021-11-15 15:40 UTC, Amoki approved these changes

2021-11-15 15:41 UTC, merged

2024-10-16 12:30 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: