Feature/visa
bimdata/platform pull request #95
Opened 2021-12-06 15:18 UTC by pvilalta

2021-12-07 18:04 UTC, pvilalta commented
Hello everyone,

Here is the first code about the Visa feature

* button into file menu to create a Visa added
* view to create a Visa added
* set-up of the route to write a Visa record into the DB done
* safe-zone when quitting the creation of a visa handled

Paul

@LrxGaelle @Kurtil @NicolasRichel @Amoki

2022-02-01 13:31 UTC, Amoki requested changes

2022-02-01 13:31 UTC, Amoki commented on src/components/specific/visa/visa-add/VisaAdd.vue
> +      const dateConform = isDateConform(dateInput);
Conform isn't English there. dateValid and isDateValid seems better

2022-02-08 09:32 UTC, merged

2024-10-16 12:30 UTC, Bimdata-io commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/bimdata/platform/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: